import {
  Accessibility,
  AirVent,
  AlarmClock,
  Amphora,
  Anchor,
  Antenna,
  Archive,
  Armchair,
  ArrowUpDown,
  Baby,
  Bath,
  BatteryCharging,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  Bell,
  BellRing,
  Bike,
  Bird,
  Blend,
  Blinds,
  Book,
  BookOpen,
  BriefcaseBusiness,
  Brush,
  Building,
  Building2,
  Cake,
  CalendarDays,
  Camera,
  Car,
  CarFront,
  Caravan,
  Castle,
  Cat,
  Cctv,
  ChefHat,
  ChevronsUpDown,
  Cigarette,
  CigaretteOff,
  CircleAlert,
  CircleParking,
  Clapperboard,
  Clock,
  CloudSun,
  Coffee,
  ConciergeBell,
  Container,
  CookingPot,
  Croissant,
  CupSoda,
  Dog,
  DoorClosed,
  DoorOpen,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  EggFried,
  Eye,
  Fan,
  Fence,
  FerrisWheel,
  FireExtinguisher,
  Fish,
  Flame,
  Flower,
  Flower2,
  Fuel,
  Gamepad2,
  GlassWater,
  Grape,
  Hammer,
  HandCoins,
  HandPlatter,
  Headphones,
  Heart,
  HeartPulse,
  Heater,
  Hop,
  Hotel,
  House,
  HousePlug,
  Key,
  KeyRound,
  Keyboard,
  Lamp,
  LampCeiling,
  LampDesk,
  Landmark,
  Laptop,
  Leaf,
  LifeBuoy,
  Lock,
  LockKeyhole,
  Luggage,
  MapPin,
  Martini,
  Microwave,
  Milk,
  MonitorPlay,
  Mountain,
  MountainSnow,
  MoveVertical,
  Music,
  Package,
  PaintRoller,
  ParkingMeter,
  PartyPopper,
  PawPrint,
  PersonStanding,
  Phone,
  Pill,
  Plane,
  PlugZap,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  Rabbit,
  Radio,
  Recycle,
  Refrigerator,
  Router,
  Sailboat,
  Salad,
  Sandwich,
  ScanFace,
  Scissors,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Shirt,
  ShowerHead,
  Signal,
  Siren,
  Smartphone,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  SprayCan,
  Sprout,
  SquareParking,
  Star,
  Stethoscope,
  Store,
  Sun,
  SunSnow,
  Sunrise,
  Sunset,
  Tent,
  TentTree,
  Thermometer,
  ThermometerSun,
  Timer,
  Toilet,
  ToyBrick,
  Trash2,
  TreePalm,
  TreePine,
  Trees,
  TriangleAlert,
  Tv,
  Umbrella,
  UmbrellaOff,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Volleyball,
  Wallet,
  Warehouse,
  WashingMachine,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { createElement } from "react";

/**
 * The single source of truth for amenity iconography.
 *
 * Curated on purpose: the admin icon picker offers exactly this set rather than all
 * ~1,500 lucide icons, so the catalog stays visually coherent, the picker needs no
 * virtualization, and `Amenity.icon` can be validated against a closed list instead
 * of accepting any string that later renders as a fallback.
 */
export interface AmenityIconGroup {
  group: string;
  icons: { key: string; label: string }[];
}

export const AMENITY_ICON_GROUPS: AmenityIconGroup[] = [
  {
    group: "Connectivity & work",
    icons: [
      { key: "wifi", label: "Wifi" },
      { key: "router", label: "Router" },
      { key: "signal", label: "Signal" },
      { key: "antenna", label: "Antenna" },
      { key: "laptop", label: "Laptop" },
      { key: "printer", label: "Printer" },
      { key: "keyboard", label: "Keyboard" },
      { key: "presentation", label: "Presentation" },
      { key: "phone", label: "Phone" },
      { key: "smartphone", label: "Smartphone" },
      { key: "monitor-play", label: "Monitor play" },
    ],
  },
  {
    group: "Heating & cooling",
    icons: [
      { key: "wind", label: "Wind" },
      { key: "air-vent", label: "Air vent" },
      { key: "fan", label: "Fan" },
      { key: "thermometer", label: "Thermometer" },
      { key: "thermometer-sun", label: "Thermometer sun" },
      { key: "snowflake", label: "Snowflake" },
      { key: "flame", label: "Flame" },
      { key: "heater", label: "Heater" },
      { key: "sun-snow", label: "Sun snow" },
      { key: "sunrise", label: "Sunrise" },
      { key: "sunset", label: "Sunset" },
      { key: "cloud-sun", label: "Cloud sun" },
    ],
  },
  {
    group: "Laundry & cleaning",
    icons: [
      { key: "shirt", label: "Shirt" },
      { key: "washing-machine", label: "Washing machine" },
      { key: "droplet", label: "Droplet" },
      { key: "droplets", label: "Droplets" },
      { key: "spray-can", label: "Spray can" },
      { key: "brush", label: "Brush" },
      { key: "trash-2", label: "Trash 2" },
      { key: "recycle", label: "Recycle" },
      { key: "sparkles", label: "Sparkles" },
    ],
  },
  {
    group: "Kitchen",
    icons: [
      { key: "cooking-pot", label: "Cooking pot" },
      { key: "refrigerator", label: "Refrigerator" },
      { key: "microwave", label: "Microwave" },
      { key: "coffee", label: "Coffee" },
      { key: "utensils", label: "Utensils" },
      { key: "utensils-crossed", label: "Utensils crossed" },
      { key: "chef-hat", label: "Chef hat" },
      { key: "blend", label: "Blend" },
      { key: "soup", label: "Soup" },
      { key: "cup-soda", label: "Cup soda" },
      { key: "wine", label: "Wine" },
      { key: "glass-water", label: "Glass water" },
      { key: "beef", label: "Beef" },
      { key: "salad", label: "Salad" },
      { key: "croissant", label: "Croissant" },
      { key: "popcorn", label: "Popcorn" },
      { key: "cake", label: "Cake" },
      { key: "egg-fried", label: "Egg fried" },
      { key: "sandwich", label: "Sandwich" },
      { key: "milk", label: "Milk" },
      { key: "beer", label: "Beer" },
      { key: "martini", label: "Martini" },
      { key: "hop", label: "Hop" },
      { key: "grape", label: "Grape" },
      { key: "wheat", label: "Wheat" },
      { key: "amphora", label: "Amphora" },
      { key: "container", label: "Container" },
    ],
  },
  {
    group: "Bathroom",
    icons: [
      { key: "bath", label: "Bath" },
      { key: "shower-head", label: "Shower head" },
      { key: "toilet", label: "Toilet" },
      { key: "scissors", label: "Scissors" },
      { key: "pill", label: "Pill" },
      { key: "stethoscope", label: "Stethoscope" },
    ],
  },
  {
    group: "Bedroom & living",
    icons: [
      { key: "bed", label: "Bed" },
      { key: "bed-double", label: "Bed double" },
      { key: "bed-single", label: "Bed single" },
      { key: "lamp", label: "Lamp" },
      { key: "lamp-desk", label: "Lamp desk" },
      { key: "lamp-ceiling", label: "Lamp ceiling" },
      { key: "blinds", label: "Blinds" },
      { key: "sofa", label: "Sofa" },
      { key: "armchair", label: "Armchair" },
      { key: "archive", label: "Archive" },
      { key: "package", label: "Package" },
      { key: "book", label: "Book" },
      { key: "book-open", label: "Book open" },
    ],
  },
  {
    group: "Entertainment",
    icons: [
      { key: "tv", label: "Tv" },
      { key: "music", label: "Music" },
      { key: "radio", label: "Radio" },
      { key: "gamepad-2", label: "Gamepad 2" },
      { key: "speaker", label: "Speaker" },
      { key: "headphones", label: "Headphones" },
      { key: "clapperboard", label: "Clapperboard" },
      { key: "toy-brick", label: "Toy brick" },
      { key: "puzzle", label: "Puzzle" },
      { key: "party-popper", label: "Party popper" },
      { key: "ferris-wheel", label: "Ferris wheel" },
      { key: "dumbbell", label: "Dumbbell" },
      { key: "volleyball", label: "Volleyball" },
    ],
  },
  {
    group: "Outdoor",
    icons: [
      { key: "sun", label: "Sun" },
      { key: "trees", label: "Trees" },
      { key: "tree-pine", label: "Tree pine" },
      { key: "tree-palm", label: "Tree palm" },
      { key: "sprout", label: "Sprout" },
      { key: "flower", label: "Flower" },
      { key: "flower-2", label: "Flower 2" },
      { key: "leaf", label: "Leaf" },
      { key: "tent", label: "Tent" },
      { key: "tent-tree", label: "Tent tree" },
      { key: "umbrella", label: "Umbrella" },
      { key: "umbrella-off", label: "Umbrella off" },
      { key: "fence", label: "Fence" },
      { key: "warehouse", label: "Warehouse" },
      { key: "hammer", label: "Hammer" },
      { key: "wrench", label: "Wrench" },
      { key: "paint-roller", label: "Paint roller" },
    ],
  },
  {
    group: "Views & location",
    icons: [
      { key: "mountain", label: "Mountain" },
      { key: "mountain-snow", label: "Mountain snow" },
      { key: "building", label: "Building" },
      { key: "building-2", label: "Building 2" },
      { key: "castle", label: "Castle" },
      { key: "landmark", label: "Landmark" },
      { key: "map-pin", label: "Map pin" },
      { key: "sailboat", label: "Sailboat" },
      { key: "anchor", label: "Anchor" },
      { key: "ship", label: "Ship" },
      { key: "fish", label: "Fish" },
      { key: "waves", label: "Waves" },
      { key: "house", label: "House" },
      { key: "house-plug", label: "House plug" },
      { key: "store", label: "Store" },
      { key: "hotel", label: "Hotel" },
    ],
  },
  {
    group: "Parking & travel",
    icons: [
      { key: "car", label: "Car" },
      { key: "car-front", label: "Car front" },
      { key: "parking-meter", label: "Parking meter" },
      { key: "circle-parking", label: "Circle parking" },
      { key: "square-parking", label: "Square parking" },
      { key: "caravan", label: "Caravan" },
      { key: "bike", label: "Bike" },
      { key: "plane", label: "Plane" },
      { key: "luggage", label: "Luggage" },
      { key: "briefcase-business", label: "Briefcase business" },
      { key: "fuel", label: "Fuel" },
      { key: "zap", label: "Zap" },
      { key: "plug-zap", label: "Plug zap" },
      { key: "battery-charging", label: "Battery charging" },
    ],
  },
  {
    group: "Safety",
    icons: [
      { key: "shield", label: "Shield" },
      { key: "shield-check", label: "Shield check" },
      { key: "shield-alert", label: "Shield alert" },
      { key: "siren", label: "Siren" },
      { key: "bell-ring", label: "Bell ring" },
      { key: "camera", label: "Camera" },
      { key: "cctv", label: "Cctv" },
      { key: "fire-extinguisher", label: "Fire extinguisher" },
      { key: "heart-pulse", label: "Heart pulse" },
      { key: "life-buoy", label: "Life buoy" },
      { key: "triangle-alert", label: "Triangle alert" },
      { key: "circle-alert", label: "Circle alert" },
    ],
  },
  {
    group: "Check-in & access",
    icons: [
      { key: "lock", label: "Lock" },
      { key: "lock-keyhole", label: "Lock keyhole" },
      { key: "key", label: "Key" },
      { key: "key-round", label: "Key round" },
      { key: "door-open", label: "Door open" },
      { key: "door-closed", label: "Door closed" },
      { key: "scan-face", label: "Scan face" },
      { key: "vault", label: "Vault" },
      { key: "clock", label: "Clock" },
      { key: "alarm-clock", label: "Alarm clock" },
      { key: "timer", label: "Timer" },
      { key: "calendar-days", label: "Calendar days" },
      { key: "concierge-bell", label: "Concierge bell" },
      { key: "hand-platter", label: "Hand platter" },
      { key: "bell", label: "Bell" },
    ],
  },
  {
    group: "Family, pets & accessibility",
    icons: [
      { key: "baby", label: "Baby" },
      { key: "users", label: "Users" },
      { key: "user", label: "User" },
      { key: "person-standing", label: "Person standing" },
      { key: "accessibility", label: "Accessibility" },
      { key: "ear", label: "Ear" },
      { key: "eye", label: "Eye" },
      { key: "arrow-up-down", label: "Arrow up down" },
      { key: "chevrons-up-down", label: "Chevrons up down" },
      { key: "move-vertical", label: "Move vertical" },
      { key: "dog", label: "Dog" },
      { key: "cat", label: "Cat" },
      { key: "paw-print", label: "Paw print" },
      { key: "bird", label: "Bird" },
      { key: "rabbit", label: "Rabbit" },
    ],
  },
  {
    group: "Rules & services",
    icons: [
      { key: "cigarette", label: "Cigarette" },
      { key: "cigarette-off", label: "Cigarette off" },
      { key: "hand-coins", label: "Hand coins" },
      { key: "wallet", label: "Wallet" },
      { key: "star", label: "Star" },
      { key: "heart", label: "Heart" },
    ],
  },
];

const COMPONENTS: Record<string, LucideIcon> = {
  "wifi": Wifi,
  "router": Router,
  "signal": Signal,
  "antenna": Antenna,
  "laptop": Laptop,
  "printer": Printer,
  "keyboard": Keyboard,
  "presentation": Presentation,
  "phone": Phone,
  "smartphone": Smartphone,
  "monitor-play": MonitorPlay,
  "wind": Wind,
  "air-vent": AirVent,
  "fan": Fan,
  "thermometer": Thermometer,
  "thermometer-sun": ThermometerSun,
  "snowflake": Snowflake,
  "flame": Flame,
  "heater": Heater,
  "sun-snow": SunSnow,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "cloud-sun": CloudSun,
  "shirt": Shirt,
  "washing-machine": WashingMachine,
  "droplet": Droplet,
  "droplets": Droplets,
  "spray-can": SprayCan,
  "brush": Brush,
  "trash-2": Trash2,
  "recycle": Recycle,
  "sparkles": Sparkles,
  "cooking-pot": CookingPot,
  "refrigerator": Refrigerator,
  "microwave": Microwave,
  "coffee": Coffee,
  "utensils": Utensils,
  "utensils-crossed": UtensilsCrossed,
  "chef-hat": ChefHat,
  "blend": Blend,
  "soup": Soup,
  "cup-soda": CupSoda,
  "wine": Wine,
  "glass-water": GlassWater,
  "beef": Beef,
  "salad": Salad,
  "croissant": Croissant,
  "popcorn": Popcorn,
  "cake": Cake,
  "egg-fried": EggFried,
  "sandwich": Sandwich,
  "milk": Milk,
  "beer": Beer,
  "martini": Martini,
  "hop": Hop,
  "grape": Grape,
  "wheat": Wheat,
  "amphora": Amphora,
  "container": Container,
  "bath": Bath,
  "shower-head": ShowerHead,
  "toilet": Toilet,
  "scissors": Scissors,
  "pill": Pill,
  "stethoscope": Stethoscope,
  "bed": Bed,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  "lamp": Lamp,
  "lamp-desk": LampDesk,
  "lamp-ceiling": LampCeiling,
  "blinds": Blinds,
  "sofa": Sofa,
  "armchair": Armchair,
  "archive": Archive,
  "package": Package,
  "book": Book,
  "book-open": BookOpen,
  "tv": Tv,
  "music": Music,
  "radio": Radio,
  "gamepad-2": Gamepad2,
  "speaker": Speaker,
  "headphones": Headphones,
  "clapperboard": Clapperboard,
  "toy-brick": ToyBrick,
  "puzzle": Puzzle,
  "party-popper": PartyPopper,
  "ferris-wheel": FerrisWheel,
  "dumbbell": Dumbbell,
  "volleyball": Volleyball,
  "sun": Sun,
  "trees": Trees,
  "tree-pine": TreePine,
  "tree-palm": TreePalm,
  "sprout": Sprout,
  "flower": Flower,
  "flower-2": Flower2,
  "leaf": Leaf,
  "tent": Tent,
  "tent-tree": TentTree,
  "umbrella": Umbrella,
  "umbrella-off": UmbrellaOff,
  "fence": Fence,
  "warehouse": Warehouse,
  "hammer": Hammer,
  "wrench": Wrench,
  "paint-roller": PaintRoller,
  "mountain": Mountain,
  "mountain-snow": MountainSnow,
  "building": Building,
  "building-2": Building2,
  "castle": Castle,
  "landmark": Landmark,
  "map-pin": MapPin,
  "sailboat": Sailboat,
  "anchor": Anchor,
  "ship": Ship,
  "fish": Fish,
  "waves": Waves,
  "house": House,
  "house-plug": HousePlug,
  "store": Store,
  "hotel": Hotel,
  "car": Car,
  "car-front": CarFront,
  "parking-meter": ParkingMeter,
  "circle-parking": CircleParking,
  "square-parking": SquareParking,
  "caravan": Caravan,
  "bike": Bike,
  "plane": Plane,
  "luggage": Luggage,
  "briefcase-business": BriefcaseBusiness,
  "fuel": Fuel,
  "zap": Zap,
  "plug-zap": PlugZap,
  "battery-charging": BatteryCharging,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "siren": Siren,
  "bell-ring": BellRing,
  "camera": Camera,
  "cctv": Cctv,
  "fire-extinguisher": FireExtinguisher,
  "heart-pulse": HeartPulse,
  "life-buoy": LifeBuoy,
  "triangle-alert": TriangleAlert,
  "circle-alert": CircleAlert,
  "lock": Lock,
  "lock-keyhole": LockKeyhole,
  "key": Key,
  "key-round": KeyRound,
  "door-open": DoorOpen,
  "door-closed": DoorClosed,
  "scan-face": ScanFace,
  "vault": Vault,
  "clock": Clock,
  "alarm-clock": AlarmClock,
  "timer": Timer,
  "calendar-days": CalendarDays,
  "concierge-bell": ConciergeBell,
  "hand-platter": HandPlatter,
  "bell": Bell,
  "baby": Baby,
  "users": Users,
  "user": User,
  "person-standing": PersonStanding,
  "accessibility": Accessibility,
  "ear": Ear,
  "eye": Eye,
  "arrow-up-down": ArrowUpDown,
  "chevrons-up-down": ChevronsUpDown,
  "move-vertical": MoveVertical,
  "dog": Dog,
  "cat": Cat,
  "paw-print": PawPrint,
  "bird": Bird,
  "rabbit": Rabbit,
  "cigarette": Cigarette,
  "cigarette-off": CigaretteOff,
  "hand-coins": HandCoins,
  "wallet": Wallet,
  "star": Star,
  "heart": Heart,
};

export const AMENITY_ICON_KEYS = Object.keys(COMPONENTS);

/** Renders a stored icon key, or null when it is unset or unknown. Returns an element
 *  rather than a component so callers never bind one to a local during render. */
export function renderAmenityIcon(
  key: string | null | undefined,
  className?: string,
) {
  const component = key ? COMPONENTS[key] : undefined;
  if (!component) return null;
  return createElement(component, { className });
}

export function isAmenityIconKey(value: unknown): value is string {
  return typeof value === "string" && value in COMPONENTS;
}

/** The icon for a stored `Amenity.icon`, or null when it is unset or no longer
 *  in the registry. Callers decide how to render the gap — the admin editor flags
 *  it as a defect, guest-facing surfaces fall back to a neutral placeholder. */
export function amenityIcon(key: string | null | undefined): LucideIcon | null {
  if (!key) return null;
  return COMPONENTS[key] ?? null;
}

/** Ranked icon suggestions for an amenity name, used by the picker's "suggested"
 *  row so adding "Elevator" offers arrow-up-down before the full grid. */
export function suggestAmenityIcons(name: string, limit = 6): string[] {
  const words = name.toLowerCase().match(/[a-z]+/g) ?? [];
  if (words.length === 0) return [];
  const scored = AMENITY_ICON_KEYS.map((key) => {
    const parts = key.split("-");
    let score = 0;
    for (const word of words) {
      if (word.length < 3) continue;
      for (const part of parts) {
        if (part === word) score += 10;
        else if (part.startsWith(word) || word.startsWith(part)) score += 4;
        else if (part.includes(word) || word.includes(part)) score += 2;
      }
    }
    return { key, score };
  }).filter((entry) => entry.score > 0);
  scored.sort((a, b) => b.score - a.score || a.key.localeCompare(b.key));
  return scored.slice(0, limit).map((entry) => entry.key);
}
