import "server-only";
import { unstable_cache } from "next/cache";
import { db } from "@/lib/db";
import generatedCatalog from "@/lib/i18n/generated-ui-strings.json";

/** Invalidated whenever translations or a language's AI-translation setting change —
 * see lib/actions/ui-translation.actions.ts and lib/actions/language.actions.ts. */
export const UI_TRANSLATIONS_TAG = "ui-translations";

/**
 * Bounded fallback on top of tag invalidation. Tag revalidation only reaches the
 * running server when it's triggered from inside it (an admin action), but
 * `scanUiStrings`/translation import also run from standalone CLI scripts at deploy
 * time (see scripts/import-reviewed-ui-translations.ts), and a separate process
 * cannot invalidate this server's cache. Without a time bound, a CLI sync would leave
 * stale translations served indefinitely. Five minutes matches the other public
 * catalogs in this codebase.
 */
const CATALOG_REVALIDATE_SECONDS = 300;

interface GeneratedUiString {
  key: string;
  sourceText: string;
}

/** The AST-extracted source literals, i.e. exactly the `source` values that `resolve`
 * is called with at every call site. Regenerated by `npm run i18n:extract` (which
 * `prebuild`/`predev` run) and enforced by `npm run i18n:check`. */
const SOURCE_TEXT_BY_KEY = new Map(
  (generatedCatalog as GeneratedUiString[]).map((entry) => [
    entry.key,
    entry.sourceText,
  ]),
);

export interface CatalogEntry {
  value: string;
  sourceTextSnapshot: string;
}

export interface LocaleCatalog {
  /** Whether the language exists and is enabled. When false the caller reverts to the
   * source language entirely (including `<html lang>`); when true but `active` is
   * false, the requested locale is kept and only the AI translations are absent. The
   * two cases are deliberately distinct — collapsing them would change the document
   * language for visitors whose language is simply not AI-translated. */
  enabled: boolean;
  /** False when the locale is unknown, disabled, or not AI-translated — callers fall
   * back to source text and let the Google Translate widget handle the page. */
  active: boolean;
  /** Full rows, snapshots included, for server-side resolution. */
  entries: Record<string, CatalogEntry>;
  /** Flattened `key -> value`, pre-filtered to entries whose snapshot still matches
   * the generated catalog. This is what gets serialized into the client payload:
   * shipping the snapshots too roughly doubled it, and the client only needed them to
   * repeat a staleness check that can be settled once, here. */
  clientMessages: Record<string, string>;
}

const DISABLED_CATALOG: LocaleCatalog = {
  enabled: false,
  active: false,
  entries: {},
  clientMessages: {},
};

/** Language is enabled, but its fixed UI text isn't AI-translated — the locale stands,
 * the page just renders source text (Google Translate handles the rest). */
const NO_AI_CATALOG: LocaleCatalog = {
  enabled: true,
  active: false,
  entries: {},
  clientMessages: {},
};

/**
 * Loads one locale's UI translations. Cached across requests: this reads every row
 * for the locale (~800 of them), and it previously ran on every single page render
 * for every non-English visitor.
 *
 * `locale` is passed in as an argument rather than read from cookies inside, because
 * request APIs like `cookies()` are not available within a cache scope.
 */
export const getLocaleCatalog = unstable_cache(
  async (locale: string): Promise<LocaleCatalog> => {
    const language = await db.language.findUnique({ where: { code: locale } });
    if (!language?.isEnabled) return DISABLED_CATALOG;
    if (!language.useAiTranslation) return NO_AI_CATALOG;

    const rows = await db.uiTranslation.findMany({
      where: { locale },
      select: { key: true, value: true, sourceTextSnapshot: true },
    });

    const entries: Record<string, CatalogEntry> = {};
    const clientMessages: Record<string, string> = {};
    for (const row of rows) {
      entries[row.key] = {
        value: row.value,
        sourceTextSnapshot: row.sourceTextSnapshot,
      };
      // A row whose snapshot no longer matches the source literal is stale — the
      // client would have rejected it and fallen back to source text anyway, so it
      // is dropped here instead of being shipped and discarded in the browser.
      if (SOURCE_TEXT_BY_KEY.get(row.key) === row.sourceTextSnapshot) {
        clientMessages[row.key] = row.value;
      }
    }

    return { enabled: true, active: true, entries, clientMessages };
  },
  ["ui-translation-catalog"],
  { revalidate: CATALOG_REVALIDATE_SECONDS, tags: [UI_TRANSLATIONS_TAG] },
);
